# Generated by Django 5.0.4 on 2024-04-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0002_bugreport_status_featurerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='priority',
            field=models.IntegerField(choices=[('prior1', 1), ('prior2', 2), ('prior3', 3), ('prior4', 4), ('prior5', 5)], default=1),
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='priority',
            field=models.IntegerField(choices=[('prior1', 1), ('prior2', 2), ('prior3', 3), ('prior4', 4), ('prior5', 5)], default=1),
        ),
    ]
