# Generated by Django 5.0.4 on 2024-04-30 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0004_alter_bugreport_priority_and_more'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BugReport', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FeatureRequest', to='tasks.task'),
        ),
    ]
