# Generated by Django 5.0.4 on 2024-04-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='status',
            field=models.CharField(choices=[('New', 'Новая'), ('In_progress', 'В работе'), ('Completed', 'Завершена')], default='Новая', max_length=50),
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='status',
            field=models.CharField(choices=[('review', 'Рассмотрение'), ('accepted', 'Принято'), ('denied', 'Отклонено')], default='Рассмотрение', max_length=50),
        ),
    ]
